version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: database
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
